FROM openjdk:17
EXPOSE 8080
ADD target/spring-boot-SpringBootDataMask-0.0.1-SNAPSHOT.jar spring-boot-SpringBootDataMask-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","./spring-boot-SpringBootDataMask-0.0.1-SNAPSHOT.jar"]